// Designed and constructed by Claudesy.
/**
 * Precision-Architected. Future-Built by Docsyanpse
 * Sentra Healthcare Artificial Intelligence
 */

/**
 * Red Flag Alert Component
 * Emergency warning banner for critical clinical conditions
 *
 * @module components/cdss/RedFlagAlert
 */

import { useState } from 'react';
import { AlertTriangle, ChevronDown, ChevronUp, Phone, Ambulance } from 'lucide-react';
import type { RedFlag } from '@/lib/iskandar-diagnosis-engine/red-flags';

// =============================================================================
// TYPES
// =============================================================================

interface RedFlagAlertProps {
  /** Red flag data */
  flag: RedFlag;

  /** Callback when alert is acknowledged */
  onAcknowledge?: (flagId: string) => void;

  /** Whether alert has been acknowledged */
  acknowledged?: boolean;

  /** Additional CSS classes */
  className?: string;
}

// =============================================================================
// CONSTANTS
// =============================================================================

const SEVERITY_CONFIG: Record<
  string,
  {
    bgClass: string;
    borderClass: string;
    textClass: string;
    icon: typeof Ambulance | typeof AlertTriangle;
    pulseClass: string;
  }
> = {
  emergency: {
    bgClass: 'bg-critical/15',
    borderClass: 'border-critical/50',
    textClass: 'text-critical',
    icon: Ambulance,
    pulseClass: 'animate-pulse',
  },
  urgent: {
    bgClass: 'bg-critical/10',
    borderClass: 'border-critical/40',
    textClass: 'text-critical',
    icon: AlertTriangle,
    pulseClass: '',
  },
  warning: {
    bgClass: 'bg-caution/10',
    borderClass: 'border-caution/40',
    textClass: 'text-caution',
    icon: AlertTriangle,
    pulseClass: '',
  },
  high: {
    bgClass: 'bg-critical/10',
    borderClass: 'border-critical/40',
    textClass: 'text-critical',
    icon: AlertTriangle,
    pulseClass: '',
  },
  medium: {
    bgClass: 'bg-caution/10',
    borderClass: 'border-caution/40',
    textClass: 'text-caution',
    icon: AlertTriangle,
    pulseClass: '',
  },
  low: {
    bgClass: 'bg-status-info/10',
    borderClass: 'border-status-info/40',
    textClass: 'text-status-info',
    icon: AlertTriangle,
    pulseClass: '',
  },
  info: {
    bgClass: 'bg-carbon-800',
    borderClass: 'border-carbon-700',
    textClass: 'text-muted',
    icon: AlertTriangle,
    pulseClass: '',
  },
};

function humanizeUiText(value: string): string {
  return value.replace(/_/g, ' ').replace(/\s+/g, ' ').trim();
}

// =============================================================================
// COMPONENT
// =============================================================================

/**
 * RedFlagAlert
 * Displays critical clinical alerts that require immediate attention
 *
 * HARDCODED SAFETY RULES — NOT AI DEPENDENT
 * These alerts are generated by deterministic rules (qSOFA, ACS, etc.)
 */
export function RedFlagAlert({
  flag,
  onAcknowledge,
  acknowledged = false,
  className = '',
}: RedFlagAlertProps) {
  const [expanded, setExpanded] = useState(flag.severity === 'emergency');

  const config = SEVERITY_CONFIG[flag.severity] || SEVERITY_CONFIG.info;
  const IconComponent = config.icon;

  return (
    <div
      className={`neu-card ${config.bgClass} border ${config.borderClass} ${config.pulseClass} ${className}`}
      role="alert"
      aria-live={flag.severity === 'emergency' ? 'assertive' : 'polite'}
    >
      {/* Header */}
      <div className="p-4">
        <div className="flex items-start gap-3">
          {/* Icon */}
          <div className={`flex-shrink-0 ${config.textClass}`}>
            <IconComponent className="w-6 h-6" />
          </div>

          <div className="flex-1 min-w-0">
            {/* Severity badge */}
            <div className="flex items-center gap-2 mb-1">
              <span
                className={`text-tiny font-semibold uppercase tracking-wider ${config.textClass}`}
              >
                {flag.severity === 'emergency'
                  ? '⚠️ DARURAT'
                  : humanizeUiText(flag.severity).toUpperCase()}
              </span>
              {acknowledged && (
                <span className="text-tiny text-muted bg-carbon-800 px-1.5 py-0.5 rounded">
                  Dikonfirmasi
                </span>
              )}
            </div>

            {/* Condition name */}
            <h3 className={`text-subtitle font-semibold ${config.textClass}`}>{flag.condition}</h3>

            {/* Brief rationale from criteria */}
            <p className="text-small text-platinum/80 mt-1 leading-snug">
              {flag.criteria_met.map((item) => humanizeUiText(item)).join('; ')}
            </p>
          </div>
        </div>

        {/* Expand/Collapse for details */}
        <button
          onClick={() => setExpanded(!expanded)}
          className="mt-3 w-full flex items-center justify-center gap-1 py-1.5 text-caption text-muted hover:text-platinum transition-colors"
          aria-expanded={expanded}
        >
          {expanded ? (
            <>
              <ChevronUp className="w-4 h-4" />
              <span>Sembunyikan Detail</span>
            </>
          ) : (
            <>
              <ChevronDown className="w-4 h-4" />
              <span>Lihat Detail & Tindakan</span>
            </>
          )}
        </button>
      </div>

      {/* Expanded: Action + ICD codes */}
      {expanded && (
        <div className="px-4 pb-4 border-t border-carbon-700/50">
          {/* Recommended action */}
          <div className="mt-3 p-3 bg-carbon-900/50 rounded-lg">
            <p className="text-caption text-muted mb-1">Tindakan yang Disarankan:</p>
            <p className={`text-small font-medium ${config.textClass}`}>{flag.action}</p>
          </div>

          {/* Related ICD codes */}
          {flag.icd_codes && flag.icd_codes.length > 0 && (
            <div className="mt-3">
              <p className="text-caption text-muted mb-1.5">Kode ICD-10 Terkait:</p>
              <div className="flex flex-wrap gap-2">
                {flag.icd_codes.map((code) => (
                  <code
                    key={code}
                    className="px-2 py-1 bg-carbon-800 rounded text-small font-mono text-pulse-500"
                  >
                    {code}
                  </code>
                ))}
              </div>
            </div>
          )}

          {/* Emergency contact (for emergency severity) */}
          {flag.severity === 'emergency' && (
            <div className="mt-4 p-3 bg-critical/10 rounded-lg border border-critical/30">
              <div className="flex items-center gap-2 text-critical">
                <Phone className="w-4 h-4" />
                <span className="text-small font-medium">Hubungi IGD RS Rujukan Segera</span>
              </div>
            </div>
          )}

          {/* Acknowledge button */}
          {onAcknowledge && !acknowledged && (
            <button
              onClick={() => onAcknowledge(flag.id)}
              className="mt-4 w-full py-2.5 rounded-lg text-small font-medium bg-carbon-800 text-platinum hover:bg-carbon-700 transition-colors border border-carbon-600"
            >
              Saya Memahami Peringatan Ini
            </button>
          )}
        </div>
      )}
    </div>
  );
}

// =============================================================================
// EXPORTS
// =============================================================================

export type { RedFlagAlertProps };
